keys:
  - &yubikey 499C66E9512BA96797CDAC410562840F5B0C9BD4
  - &MacBook 9899f95e2ce795ccfe83597b653adbbb164a953a
  - &Felix-Desktop 90f10c0f273bffff541691fff10afdd5a8360aeb
creation_rules:
  - path_regex: nixos/secrets/.*
    key_groups:
    - pgp:
        - *yubikey
        - *MacBook
        - *Felix-Desktop
