keys:
  - &yubikey 499C66E9512BA96797CDAC410562840F5B0C9BD4
  - &MacBook abc1ca1c95a95721a5fada00d76ed72317789c74
creation_rules:
  - path_regex: nixos/secrets/.*
    key_groups:
    - pgp:
        - *yubikey
        - *MacBook
