keys:
  - &yubikey 499C66E9512BA96797CDAC410562840F5B0C9BD4
  - &MacBook 708be9ec328b14b8a2246a10c64ad1946d3c842d
  - &MacBookAge age1d5smh54jg270ztcrr2aylz2crxxz4rp0tsz0kgj3n43ervnlwezsgnvwe0
creation_rules:
  - path_regex: nixos/secrets/.*
    key_groups:
    - pgp:
        - *yubikey
        - *MacBook
      age:
        - *MacBookAge
